# Generated by Django 4.1.1 on 2022-09-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=20)),
                ('Emp_salary', models.FloatField()),
                ('DOJ', models.DateField()),
                ('Emp_address', models.TextField()),
                ('Emp_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelliApp.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
