# Generated by Django 4.1.1 on 2022-09-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_salary', models.FloatField()),
                ('doj', models.DateField()),
                ('emp_address', models.TextField()),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depEmpl.department')),
            ],
        ),
    ]
